Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -15,7 +15,7 @@ jobs:
   unit_test:
     name: Test
     runs-on: macos-13
-    timeout-minutes: 60
+    timeout-minutes: 10
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -25,7 +25,12 @@ jobs:
 
       - name: Run Test
         run: |
-          swift test | xcbeautify
+          if swift test | xcbeautify; then
+            echo "Success: All tests passed!"
+          else
+            echo "Error: Some tests failed!"
+            exit 1
+          fi
 
       - name: Check Consistency of Example and Readme
         run: |
